### ISSUE TITLE
Right now the test are reporting if something fails/works

### ISSUE THREAD

**Issue by ccoVeille** [alingse/go-linter-runner#4]
It's good, but what could be way better would be to track the number of errors per repository

Is there a way to a return metadata or to store the number of errors

**Comment by ccoVeille** [comment]
I would expect to be able to solve issues as the one reported here

https://github.com/Antonboom/testifylint/issues/98#issue-2320900512

**Comment by ccoVeille** [comment]
Or better find a way to download results from all reports (project) that failed

**Comment by alingse** [comment]
Yes, I'm going to do such things, I want to use a result collector, like a google sheet ? or a web server ?

1. `submit.sh` -> `a lot of actions` -> `upload the failed result to a API`  -> `a google sheet` / `some total json`

the step 3 I'm going to use `pipedream` (https://pipedream.com/apps/google-sheets )or others public API's , or just use the github no public api

but I'm going vacation

**Comment by ccoVeille** [comment]
Maybe considering a GitHub Page would be simpler, or to publish the result as a PR/issues/discussion comments, where you will attach the results as a file.

**Comment by alingse** [comment]
@ccoVeille I have add a feature to create comment on the config issue, see https://github.com/alingse/go-linter-runner/issues/2 comments

**Comment by ccoVeille** [comment]
I just saw it, it's impressive, it's created
