### ISSUE TITLE
Run `revive:92c3209` with "modifies-value-receiver linter"

### ISSUE THREAD

**Issue by alingse** [alingse/go-linter-runner#8]

**Comment by ccoVeille** [comment]
Did it work?

**Comment by ccoVeille** [comment]
I think I know why nothing is reported

You need to define a config file that will enable modify value by receiver linter

And the you could pass

revive  --config your/file

I'm unsure it's easy to do with your runner.

BTW it's great you created another repository for launching the tests

**Comment by alingse** [comment]
I have fix it @ccoVeille and start run at https://github.com/alingse/go-linter-runner-example/issues/1

The comments in the first half under the issue are missing URLs because I didn't adapt the output of the revive linter. You can jump to the end to see the latest comments, which can directly link to the corresponding code locations
